DROP DATABASE IF EXISTS favlinksAPI;
CREATE DATABASE favlinksAPI;

\c favlinksAPI;

DROP TABLE IF EXISTS favlinks;


CREATE TABLE favlinks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL
);